### ISSUE TITLE
Move unused helpers into Library

### ISSUE THREAD

**Issue by johndjameson** [mvcss/mvcss#11]
Let's remove the following helpers from MVCSS core and put them in the Library:

## Mixins

- `font-face` mixin

## Extends

- `debug`
- `ellipsis`
- `ir`

**Comment by drewbarontini** [comment]
:+1:

**Comment by drewbarontini** [comment]
Any objections?

cc: @mvcss/contributors

**Comment by jordanwade** [comment]
Nope

**Comment by drewbarontini** [comment]
Also, they are added to the Library in https://github.com/mvcss/library/commit/b308bd6cf9ac6fa566c2763f8cf76d72acd06979, which I'll merge into `master` once we finalize v4.1.
