### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/mvcss#13]
Per [More Transparent UI Code with Namespaces](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/), there's a lot of valid points and considerations for namespacing all classes. For me, it's primarily about search. Right now, when searching across a project for a repo-wide rename, it's a nightmare for generically named classes. However, the other points are valid as well, and something I'd love to open up as a discussion. Obviously, this is v5 feature due to the "API" changes it would make.

I could see us doing namespaces like this:

- `u-`: for Tools and Helper `@extend`s.
- `c-` or `o-` (as the article describes for generic objects, which Components are for us): for Components (@nickawash - I know `c-` will give you and I shivers :wink:).
- `s-`: for Structures.
- `is-`, `has-`: we already follow these conventions.
- `js-`: we already follow this convention.
- `qa-`: for class hooks used for things like integration tests.

I'll leave this by pointing out that, if we adopted the `o-` namespace for Components, it would be called `.o-well`. That is all.

**Comment by johndjameson** [comment]
We've run into issues with third-party libraries not namespacing their classes. By prefixing our own classes, we can effectively sidestep that issue in addition to improving our architecture. :+1: 

Also, heading classes can be a bit weird, but we can probably throw them in with "Tools and Helpers":

```
u-h1
u-h2
u-h3
u-h4
```

**Comment by nickawalsh** [comment]
Sounds like a good plan, I'll need to give it a shot in a project somewhere. Part of me wants `t-` for tools, unless you're trying to mirror other conventions for new converts.

The heading issue is something else entirely. Like the issue you just opened for `link`, I've been finding myself making a `heading` component more and more.

**Comment by drewbarontini** [comment]
Yeah, I thought `t-` at first, but since the extends and heading classes are using the prefix as well, `u-` seemed to be more consistent to encompass all of them.

A `link` structure has been working well. I _really_ like the idea of a `heading` component. I'll have to try that for all the heading variations that occur.

**Comment by olivierlacan** [comment]
![selfie-3](http://i.imgur.com/tQvUWVf.gif)

**Comment by drewbarontini** [comment]
Settled with #32
