### ISSUE TITLE
Percentage font size at root

### ISSUE THREAD

**Issue by johndjameson** [mvcss/mvcss#14]
We currently specify our root font size in pixels, rather than fluid units. As a result, changing the font size in a browser's settings doesn't have any affect on the text's displayed size.

```
html
  // ...
  font-size: $b-fontSize // 16px
```

By switching to fluid units, we can improve customizability and accessibility for users who prefer a different font size.

```
html
  // ...
  font-size: percentage($b-fontSize/16px)  // 100%
```

**Comment by drewbarontini** [comment]
@johndjameson I know you saw some possible caveats with this. Are you still in favor of this approach, or should we close the issue and discuss later?

**Comment by johndjameson** [comment]
Let's hold off on this for now.
