### ISSUE TITLE
Add font-size function for pixel-to-percent conversion

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/mvcss#16]
To make it easier to deal with the percentage `font-size`, we can add a `font-size` function:

```sass
// ----- Font Size ----- //
// -> Converts pixel value to a percentage
//
// $target - the target pixel size
// $context - the context font-size

@function font-size($target, $context: $b-fontSize)
  @return percentage($target / $context)
```

And then in `_config.sass`:

```sass
$b-fontSize-xs: font-size(12px)
$b-fontSize-s: font-size(14px)
$b-fontSize-l: font-size(18px)
$b-fontSize-xl: font-size(24px)
$b-fontSize-h1: font-size(32px)
$b-fontSize-h2: font-size(24px)
$b-fontSize-h3: font-size(20px)
$b-fontSize-h4: font-size(18px)
```

The percentages will change slightly off of what they are now, but this should make it line up with using pixels with the `em()` function.

I've added this to the `4_1_0` branch, but I can roll back if there are any :-1: on this.

**Comment by johndjameson** [comment]
:+1:

**Comment by johndjameson** [comment]
We can ignore this in v5, and I'm fine with leaving it out of v4.1, too.

**Comment by johndjameson** [comment]
This was already added in the branch, so I’m closing this and merging in v4.1.
