### ISSUE TITLE
Font size variables

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/mvcss#24]
How should we handle `$t-fontSize` variables with `-xs`, `-s`, etc.? We should keep it consistent with the changes to `$b-space`.

**Comment by nickawalsh** [comment]
Just hit this issue too. Technically, if we're staying consistent, it'd look like:

```scss
$t-fontSize: 16px;
$t-fontSize-2: $t-fontSize * 2;
$t-fontSize-25: $t-fontSize * 2.5;
// etc
```

But that'd be odd. I'm not sure font sizes, line heights, letter spacing, etc. etc. line up to a root unit like spacing typically does. Maybe they continue to be relative measures (`-m`, `-s`, etc)? @johndjameson @dangodev

**Comment by johndjameson** [comment]
I think we should treat font sizes like colors and focus on easy-to-remember variable names.

We want to avoid variables like these, which make sense in `config` but are difficult to author elsewhere in the codebase.

```scss
// 16px golden ratio scale

$t-fontSize-062: $t-fontSize * 0.62; // 10px
$t-fontSize: 16px;
$t-fontSize-16: $t-fontSize * 1.6; // 26px
$t-fontSize-26: $t-fontSize * 2.6; // 42px
$t-fontSize-42: $t-fontSize * 4.2; // 67px
```

These _could_ work, but are redundant and still hard to remember. Even worse, _you can't make snippets for them:_ :scream: 

```scss
$t-fontSize-10: 10px;
$t-fontSize: 16px;
$t-fontSize-26: 26px;
$t-fontSize-42: 42px;
$t-fontSize-67: 67px;
```

So I'm thinking named sizes are worth sticking to, but this time using explicit pixel values. They're easy to recognize in markup and especially easy to remember across code bases — just like _red_, _green_, and _blue_:

```scss
$t-fontSize: 16px;
$t-fontSize-s: 10px;
$t-fontSize-l: 26px;
$t-fontSize-xl: 42px;
$t-fontSize-xxl: 67px;
```

If you need the occasional random size for a tool class, you can toss it in a variable so it's documented and reusable:

```scss
$t-fontSize-18: 18px;
$t-fontSize-34: 34px;
$t-fontSize-100: 100px;
```

```haml
%p.tc-red.ts18.tsl_m This red text is 18px on mobile then large at $g-m.
```

**Comment by nickawalsh** [comment]
:+1:

**Comment by drewbarontini** [comment]
:fist:

**Comment by drewbarontini** [comment]
No changes are needed in the `v5_alpha` branch then. Closing and we can reference this later when updating the documentation.
