### ISSUE TITLE
v5 Rebrand

### ISSUE THREAD

**Issue by jhnwlsn** [mvcss/mvcss#43]
Here's my first decent shot at the v5 rebrand. Would love some feedback. Here's the concept for the landing/homepage:

![mvcss-01](https://cloud.githubusercontent.com/assets/2472911/11753807/5def3f72-a015-11e5-9108-94f3eddcc26a.jpg)

A few notes regarding the design:
- We should change MVCSS to Mvcss as a nod to the proper way to capitalize Sass and Haml
- Still working through colors on the illustration
- Probably shouldn't do an actual logo or anything as it's a resource for people, not a product.

Finally, I'd like us to at least discuss changing the name, for a few reasons:
1. The name "Modular View" is too unclear.
2. When paired with a "v5" tag, it might just seem like we are trying to hold on to something for a little too long.
3. From what I've heard, and even seen recently, MVCSS has changed drastically since it's first incarnation.

**Comment by nickawalsh** [comment]
Love the colors and the look. I'd love to see a font further from Helvetica to give it some character.

I'm up for a name change.. if we can think of one.

**Comment by drewbarontini** [comment]
I'm liking this direction. I'm personally not a fan of the "Mvcss" spelling. I'd have trouble with that, but I'm definitely up for discussing other names, if anyone has ideas.

**Comment by jordanwade** [comment]
Nice! I love the overall concept of the landing page! The abstract design elements remind me a little too much of the Node.js Hexagon style thing...maybe we can just change them up a bit. Or, I wonder if we could keep going with the architecture/construction(Bagger 288) and develop a cohesive brand.To me MVCSS is all about a great CSS architecture. It makes me think of stuff like this, just a random thought.
![image](https://cloud.githubusercontent.com/assets/2528817/11824582/953981fa-a348-11e5-8038-4967d3980a25.png)

I don't have any ideas for a name change, but I'm open to it.

**Comment by johndjameson** [comment]
It has been six months, so let’s call this one out of scope for v5.
