### ISSUE TITLE
Separate long files into partials

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/mvcss#9]
Another @johndjameson idea is to split out Tool sections into their own files.

- `foundation/tools/_background.sass`
- `foundation/tools/_display.sass`
- `foundation/tools/_margin.sass`
- `foundation/tools/_padding.sass`
- `foundation/tools/_position.sass`
- `foundation/tools/_rounding.sass`
- `foundation/tools/_text.sass`

While it's not a huge concern in the core `foundation/_tools.sass` file, larger projects quickly grow tool classes, which makes the file quite large and unwieldy.

Another option here, and my preferred solution, is to amend the documentation to mention that, if your Foundation files become unmanageably large, to create a new directory, and break the files into further partials. For example, the config file would fall under this.

1. Create `foundation/config` directory. (keeping `foundation/_config.sass`)
2. Create `foundation/config/_fonts.sass`, `foundation/config/_colors.sass`, etc.
3. `@import` those new partials into `foundation/_config.sass`, like below.

```sass
// *************************************
//
//   Config
//   -> Fonts, Variables
//
// *************************************

@import foundation/config/fonts
@import foundation/config/colors
@import foundation/config/base
@import foundation/config/components
@import foundation/config/structures
/ ...
```

This is something we don't _have to_ mention, but it's always better to document the convention when we can.

Thoughts?

cc: @mvcss/contributors

**Comment by johndjameson** [comment]
Solid. I think conditionally splitting long files into subtrees addresses both issues. :+1:

**Comment by drewbarontini** [comment]
Alright, closing this since it's an update to the documentation. Issue added in that repo.
